# Generated by Django 3.2.6 on 2021-08-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sudents',
            new_name='student',
        ),
    ]
