# Generated by Django 3.2.6 on 2021-08-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
